name: RulesUI
author: Antaxio
main: Antaxio\RulesUI
version: 0.1
description: Abonnez vous a ma chaine ytb AntaxioYT!
api: [3.0.0]
commands:
    rules:
        default: true
        description: ยง4Rules ui test by antaxio test 1
